apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-external-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: datadog-secretstore
    kind: SecretStore
  target:
    name: datadog-secret
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: datadog-keys
        property: api-key
    - secretKey: app-key
      remoteRef:
        key: datadog-keys
        property: app-key
