apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-cluster
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: cluster-generator-first-app
    spec:
      destination: 
        namespace: cluster-generator-first-app
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/chiemerieezechukwu/argocd-app-config
        targetRevision: HEAD
        path: charts/first-helm-chart/
        helm:
          values: |
            message: {{ metadata.annotations.test-message }}
            arn: {{ metadata.annotations.test-arn }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true