apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            purpose: cluster-datastore
  goTemplate: true
  template:
    metadata:
      name: cluster-generator-only-app
    spec:
      destination:
        namespace: cluster-generator-first-app
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/chiemerieezechukwu/argocd-app-config
        targetRevision: HEAD
        path: charts/first-helm-chart/
        helm:
          values: |
            test-annotation: {{ index .metadata.annotations "test-annotation" }}
            message: {{ index .metadata.annotations "test-message" }}
            random-pet-1: {{ index .metadata.annotations "custom-value-1" }}
            random-pet-2: {{ index .metadata.annotations "custom-value-2" }}
            random-pet-3: {{ index .metadata.annotations "custom-value-3" }}
            random-pet-4: {{ index .metadata.annotations "custom-value-4" }}
            random-pet-5: {{ index .metadata.annotations "custom-value-5" }}
            list-of-pets: {{ index .metadata.annotations "list-all-pets" }}
            test: {{ splitList "," "a,b,c" }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
