apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            purpose: cluster-datastore
  template:
    metadata:
      name: cluster-generator-only-app
    spec:
      destination: 
        namespace: cluster-generator-first-app
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/chiemerieezechukwu/argocd-app-config
        targetRevision: HEAD
        path: charts/first-helm-chart/
        helm:
          values: |
            test-annotation: {{ metadata.annotations.test-annotation }}
            message: {{ metadata.annotations.test-message }}
            random-pet-1: {{ metadata.annotations.custom-value-1 }}
            random-pet-2: {{ metadata.annotations.custom-value-2 }}
            random-pet-3: {{ metadata.annotations.custom-value-3 }}
            random-pet-4: {{ metadata.annotations.custom-value-4 }}
            random-pet-5: {{ metadata.annotations.custom-value-5 }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true