apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/manage-by: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/chiemerieezechukwu/argocd-app-config
    targetRevision: HEAD
    path: charts/argocd/
    helm:
      values: |
        argo-cd:
          global:
            image:
              tag: v2.12.6
      valueFiles:
        - values.yaml
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
