apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiemerieezechukwu/argocd-app-config
    targetRevision: HEAD
    path: charts/grafana/
    helm:
      values: |
        grafana:
          readinessProbe:
            initialDelaySeconds: 37
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
