apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chiemerieezechukwu/argocd-app-config
    targetRevision: HEAD
    path: charts/random/
  destination:
    server: https://kubernetes.default.svc
    namespace: random
  syncPolicy:
    automated:
      prune: true
      selfHeal: true