apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
type: application
version: 6.7.10
appVersion: v2.7.18

dependencies:
  - name: argo-cd
    version: 6.7.10
    repository: https://argoproj.github.io/argo-helm
