apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
type: application
version: 6.11.1
appVersion: v2.11.2

dependencies:
  - name: argo-cd
    version: 6.11.1
    repository: https://argoproj.github.io/argo-helm
