argo-cd:
  configs:
    cm:
      url: https://localhost:8080

      dex.config: |

        connectors:
        # GitHub example
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 7a7f9b02baa8d2cb8a3f
            clientSecret: $argo-github-secret:dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
            orgs:
            - name: chiemerieezechukwu
